# TensorFlow Basics

## TensorFlow Basic Syntax

Tensor is an  dimensioinal array

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.13.1


In [4]:
hello = tf.constant("Hello")
world = tf.constant("World")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

This is a tensor object

In [6]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In order to print hello, we need to run it inside a session

In [19]:
# with: it opens a session, runs a block of code and then closes it
with tf.Session() as sess: # everything inside is tf operations which we can run
    result = sess.run(hello + " " + world)

In [20]:
print(result) # The b represents an 8 bytes literal

b'Hello World'


In [11]:
a = tf.constant(10)
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

Tensorflow is keeping track of how many times it is executing. However, it has not run anyting yet

In [15]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [16]:
result

30

Another exampe

In [21]:
const = tf.constant(10)

In [23]:
fill_mat = tf.fill((4, 4), 10)

In [24]:
myzeros = tf.zeros((4,4))

In [25]:
myones = tf.ones((1,1))

In [26]:
myrandn = tf.random_normal((4,4), mean=0, stddev=1.0)
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

None of these have been executed yet

Normally these are run in 'with tf.Session():' blocks, but this time lets do it in an interactive session which is pretty useful in a notebook setting as I'm doing here. This allows you to constantly call it in multiple cells

In [28]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [30]:
# interactive session
sess = tf.InteractiveSession()

In [31]:
for op in my_ops:
    print(sess.run(op))

10
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.]]
[[-2.0431619e+00 -4.6262330e-01 -9.2485875e-01  1.2744379e+00]
 [-1.0767150e+00  9.2724542e-04  1.6895399e+00 -7.5336075e-01]
 [ 9.9434209e-01  1.6748925e-01 -1.3600149e+00 -2.9497912e+00]
 [ 2.5455034e+00 -1.0191886e+00  3.1780142e-02 -1.3886492e+00]]
[[0.5248374  0.7741784  0.9002296  0.42293096]
 [0.8421005  0.7968068  0.02918243 0.5798267 ]
 [0.62355375 0.8180219  0.47544038 0.677228  ]
 [0.04847252 0.01394439 0.00209475 0.47406363]]


In [32]:
# Another obvious way
for op in my_ops:
    result = sess.run(op)
    print(result)
    print()

10

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1.]]

[[-1.4469929   0.709865    0.59704864  0.52470887]
 [-0.21249002  1.4059967  -1.9450059   0.6538121 ]
 [ 1.0496922  -0.7041966   0.7150393  -0.07290984]
 [ 0.5758956   0.46982032 -0.7771644   0.8691724 ]]

[[0.86273956 0.8351594  0.6097683  0.26790154]
 [0.48629844 0.84263825 0.51696455 0.61142385]
 [0.0071795  0.25970316 0.065925   0.22588861]
 [0.40171325 0.6983063  0.70014215 0.12890589]]



Here, the same session is running in multiple cells and there is no need of a common block of code enclosed in "with tf.Session() as sess:"

But the formal way to run is with a block of code as shown first

Matrix Multiplication Example

In [34]:
a = tf.constant([[1,2],
                [3,4]])

In [35]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [36]:
b = tf.constant([[10], [100]])

In [37]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [38]:
result = tf.matmul(a, b)

In [39]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

Typicaly you need to do this in a session block but our InteractiveSession() is still running

In [41]:
result.eval() # This is another way to evaluate the result without using the sess

array([[210],
       [430]], dtype=int32)

In [42]:
sess.close()

In [44]:
result.eval() # This gives a result as the session got closed.

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

This means that eval() uses a session in the background and does not run without it as now sess is inactive

## TensorFlow Graphs

In tf graph, each node is an operation with possible input that supplies an output

You know what? I am gonna do that in a different file